### ISSUE TITLE
Minh: Task 3

### ISSUE THREAD

**Issue by MasterPi-2124** [notional-labs/monitor-uptime-tool#11]
- [x] Take over Son work on fixing chains
- [x] redirect chain-not-found route
- [x] Add addresses
- [x] Attempt to merge ping-test to develop (create a separate branch called ping-test-fix-conflict-develop to fix conflict on both develop and ping-test)

**Comment by nghuyenthevinh2000** [comment]
For the task 4:

1. Do not touch fetch.js
2. Do not touch store.js
