### ISSUE TITLE
Project Validator Feature Suspension: New features in ping.pub

### ISSUE THREAD

**Issue by masterpi007** [notional-labs/monitor-uptime-tool#12]
Mr Jacob found that we can monitor every chain on pingpub of notional, so validator monitoring is not needed. But there are still some chains not shown in ping.pub, so we will instead work with ping.pub team by making pull requests for new chains. About the relayer, we still need that so the work is now mainly focused on the relayer.

**Comment by nghuyenthevinh2000** [comment]
nope, no suspension at all. We continue to do stuffs.

About the stuff with ping.pub, we build relayer monitor and pr it to ping.pub
