### ISSUE TITLE
Minh: task1

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/monitor-uptime-tool#2]
pruning unnecessary UI and related features

only prune in folder views and routers. If want to extend pruning area, direct message (DM) me

deliverables: a Functioning Minimal website

**Comment by MasterPi-2124** [comment]
https://github.com/notional-labs/monitor-uptime-tool/commit/57e403f745d9581cee24294b5596d0615f8219ba

**Comment by nghuyenthevinh2000** [comment]
Investigate further into package lang that you have pruned. To see if there is any impact.

![Screenshot from 2021-12-02 17-30-59](https://user-images.githubusercontent.com/23058164/144405028-f20b390f-9f50-41a2-8edd-6b1175821241.png)

leftover stuffs in NavBar to deal with

**Comment by MasterPi-2124** [comment]
Idk, is that done yet? God knows that.

**Comment by nghuyenthevinh2000** [comment]
reminder: to be reviewed on tomorrow
